# Generated by Django 4.2.13 on 2024-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=100, verbose_name='密码')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
