# Generated by Django 4.2.13 on 2024-06-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_avatar_url',
            field=models.CharField(default='', max_length=255, verbose_name='用户头像地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=12, verbose_name='用户账号'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_mail',
            field=models.CharField(default='', max_length=255, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=255, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_tel',
            field=models.CharField(default='', max_length=255, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='密码'),
        ),
    ]
