# Generated by Django 4.2.13 on 2024-06-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_username_user_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docx',
            fields=[
                ('DocxName', models.CharField(max_length=255, verbose_name='论文名称')),
                ('FileName', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='论文版本名称')),
                ('UserId', models.CharField(max_length=255, verbose_name='用户ID')),
                ('UploadTime', models.CharField(max_length=255, verbose_name='上传时间')),
                ('Address', models.CharField(max_length=255, verbose_name='存储地址')),
            ],
            options={
                'db_table': 'docx',
            },
        ),
        migrations.CreateModel(
            name='DocxVersion',
            fields=[
                ('DocxName', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='用户ID_文档名')),
                ('UserId', models.CharField(max_length=255, verbose_name='用户ID')),
                ('CreateTime', models.DateTimeField(verbose_name='创建时间')),
                ('TableName', models.CharField(max_length=255, verbose_name='存储文件信息的数据表名')),
                ('Address', models.CharField(max_length=255, verbose_name='该版本论文所在的目录')),
                ('neglect', models.FloatField(verbose_name='忽视率')),
                ('Iteration', models.FloatField(verbose_name='小版本增加率')),
                ('version', models.FloatField(verbose_name='大版本增加率')),
                ('remind', models.IntegerField(verbose_name='论文是否正确率')),
                ('bigversion', models.IntegerField(verbose_name='大版本号')),
                ('smallversion', models.IntegerField(verbose_name='小版本号')),
            ],
            options={
                'db_table': 'docxversion',
            },
        ),
    ]
