# Generated by Django 4.2.13 on 2024-06-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_docx_docxversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_avatar_url',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='用户头像地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mail',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_tel',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='电话号码'),
        ),
    ]
