# Generated by Django 4.2.13 on 2024-06-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_id_alter_user_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docxversion',
            name='CreateTime',
            field=models.CharField(max_length=255, verbose_name='创建时间'),
        ),
    ]
